In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../00_datasets/dataset_output/include50/include50_openpose.csv")

In [3]:
df

,Unnamed: 0,category,video_name,frame,hand_0_0_x,hand_0_0_y,hand_0_0_z,hand_0_1_x,hand_0_1_y,hand_0_1_z,...,pose_22_y,pose_22_z,pose_23_x,pose_23_y,pose_23_z,pose_24_x,pose_24_y,pose_24_z,missing_hand,missing_face
0,0,1. loud,Adjectives\1. loud\MVI_5177.MOV,0,0.604532,0.777408,0.363928,0.591513,0.806553,0.604357,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
1,1,1. loud,Adjectives\1. loud\MVI_5177.MOV,1,0.604505,0.778173,0.343903,0.592441,0.805626,0.555680,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
2,2,1. loud,Adjectives\1. loud\MVI_5177.MOV,2,0.605294,0.771403,0.325611,0.592764,0.803480,0.586634,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
3,3,1. loud,Adjectives\1. loud\MVI_5177.MOV,3,0.605031,0.767677,0.338972,0.592407,0.804147,0.588775,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
4,4,1. loud,Adjectives\1. loud\MVI_5177.MOV,4,0.605058,0.762204,0.320969,0.592571,0.800129,0.619108,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260611,201189,9. Technology,Society\9. Technology\MVI_8953.MP4,68,0.565773,0.760904,0.681224,0.557107,0.776311,0.673468,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
260612,201190,9. Technology,Society\9. Technology\MVI_8953.MP4,69,0.565758,0.760145,0.674747,0.556263,0.776291,0.695618,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
260613,201191,9. Technology,Society\9. Technology\MVI_8953.MP4,70,0.564912,0.758893,0.645380,0.555963,0.775526,0.746233,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
260614,201192,9. Technology,Society\9. Technology\MVI_8953.MP4,71,0.564232,0.759607,0.657207,0.554870,0.776251,0.699390,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
260615,201193,9. Technology,Society\9. Technology\MVI_8953.MP4,72,0.563822,0.760289,0.648267,0.554871,0.776202,0.702564,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False

In [7]:
signs = list(df["category"].unique())
[i.split(". ")[-1].capitalize() for i in signs]

['Loud',
 'Mean',
 'Rich',
 'Poor',
 'Thick',
 'Thin',
 'Expensive',
 'Cheap',
 'Flat',
 'Curved',
 'Male',
 'Quiet',
 'Female',
 'Tight',
 'Loose',
 'High',
 'Low',
 'Soft',
 'Hard',
 'Deep',
 'Shallow',
 'Clean',
 'Happy',
 'Dirty',
 'Strong',
 'Weak',
 'Dead',
 'Alive',
 'Heavy',
 'Light',
 'Famous',
 'Sad',
 'Beautiful',
 'Ugly',
 'Deaf',
 'Long',
 'Short',
 'Blind',
 'Tall',
 'Wide',
 'Narrow',
 'Big large',
 'Small little',
 'Slow',
 'Fast',
 'Hot',
 'Cold',
 'Warm',
 'Nice',
 'Cool',
 'New',
 'Old',
 'Young',
 'Good',
 'Bad',
 'Wet',
 'Dry',
 'Sick',
 'Healthy',
 'Dog',
 'Cat',
 'Fish',
 'Bird',
 'Cow',
 'Mouse',
 'Horse',
 'Animal',
 'Hat',
 'Dress',
 'Suit',
 'Skirt',
 'Shirt',
 'T-shirt',
 'Pant',
 'Shoes',
 'Pocket',
 'Clothing',
 'Sunday',
 'Monday',
 'Tuesday',
 'Wednesday',
 'Thursday',
 'Friday',
 'Saturday',
 'Today',
 'Tomorrow',
 'Yesterday',
 'Week',
 'Month',
 'Year',
 'Hour',
 'Minute',
 'Second',
 'Morning',
 'Afternoon',
 'Evening',
 'Night',
 'Time',
 'Clock',
 'Lamp',
 'Fan',
 'Cell phone',
 'Computer',
 'Laptop',
 'Screen',
 'Camera',
 'Television',
 'Radio',
 'Hello',
 'How are you',
 'Alright',
 'Good morning',
 'Good afternoon',
 'Good evening',
 'Good night',
 'Thank you',
 'Pleased',
 'Table',
 'Chair',
 'Bed',
 'Dream',
 'Window',
 'Door',
 'Bedroom',
 'Kitchen',
 'Bathroom',
 'Pencil',
 'Pen',
 'Photograph',
 'Soap',
 'Book',
 'Page',
 'Key',
 'Paint',
 'Letter',
 'Paper',
 'Lock',
 'Telephone',
 'Bag',
 'Box',
 'Gift',
 'Card',
 'Ring',
 'Tool',
 'Teacher',
 'Student',
 'Lawyer',
 'Doctor',
 'Patient',
 'Waiter',
 'Secretary',
 'Priest',
 'Police',
 'Soldier',
 'Artist',
 'Author',
 'Manager',
 'Reporter',
 'Actor',
 'Job',
 'Plane',
 'Car',
 'Truck',
 'Bicycle',
 'Bus',
 'Boat',
 'Train ticket',
 'Transportation',
 'Train',
 'Son',
 'Daughter',
 'Mother',
 'Father',
 'Parent',
 'Baby',
 'Man',
 'Woman',
 'Brother',
 'Sister',
 'Family',
 'Grandfather',
 'Grandmother',
 'Husband',
 'Wife',
 'King',
 'Queen',
 'President',
 'Neighbour',
 'Boy',
 'Girl',
 'Child',
 'Adult',
 'Friend',
 'Player',
 'Crowd',
 'City',
 'House',
 'Street or road',
 'Train station',
 'Restaurant',
 'Court',
 'School',
 'Office',
 'University',
 'Park',
 'Store or shop',
 'Library',
 'Hospital',
 'Temple',
 'Market',
 'India',
 'Ground',
 'Bank',
 'Location',
 'I',
 'You',
 'He',
 'She',
 'It',
 'We',
 'You (plural)',
 'They',
 'Summer',
 'Spring',
 'Winter',
 'Fall',
 'Season',
 'Monsoon',
 'Religion',
 'Energy',
 'War',
 'Peace',
 'Attack',
 'Election',
 'Newspaper',
 'Gun',
 'Sport',
 'Exercise',
 'Ball',
 'Death',
 'Price',
 'Sign',
 'Science',
 'God',
 'Medicine',
 'Money',
 'Bill',
 'Marriage',
 'Team',
 'Race (ethnicity)',
 'Technology']

In [8]:
len(signs)

251

In [9]:
signs = df["category"].unique()
for i in range(78):
    if i not in signs:
        print(i)

0
12
19
28
33
35
45
46
53
73
75

In [1]:
import json
import os
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score
import functools

In [27]:
dataset_name = "minds"

In [28]:
if dataset_name == "minds":
#     refs = [str(i) for i in range(39, 44)]
    refs = [str(i) for i in range(49, 54)]
    person_range = range(1, 13)

if dataset_name == "ufop":
    refs = [str(i) for i in range(44, 49)]
    person_range = range(1, 6)

In [29]:
refs

['49', '50', '51', '52', '53']

In [30]:
all_results = {}
for ref in refs:
    results = []
    results_path = f"../99_model_output/results/{ref}/{dataset_name}/"
    for file in os.listdir(results_path):
        if file.endswith(".json"):
            with open(os.path.join(results_path, file), "r") as f:
                results.append(json.load(f))
    all_results[ref] = results

In [31]:
def get_result_by_validation_person(person, results):
    for result in results:
        if result["validate_people"] == [person]:
            return result
    print(f"Not found for person {person}")
    return None

In [32]:
def get_metric(y_true, y_pred, metric, average):
    if metric == accuracy_score:
        return metric(y_true, y_pred)
    else:
        return metric(y_true, y_pred, average=average, zero_division=0)

def get_average_metrics(metric, average):
    values = []
    for r in results:
        y_true = r["true_labels"]
        y_pred = r["predicted_labels"]
        values.append(get_metric(y_true, y_pred, metric, average))
    return values

def print_metrics(metric, average):
    metric_results = get_average_metrics(metric, average)
    print("=" * 10)
    if average is not None:
        print(average, metric.__name__)
    else:
        print(metric.__name__)
    average = sum(metric_results) / len(metric_results)
    std = np.std(metric_results)
    print("Average:", average)
    print("std: ", std)
    print(round(average, 2), "$\pm$", round(std, 2))
    print("=" * 10)

In [33]:
data = []
for validate_person in person_range:
#     print(f"fold {validate_person}")
    accuracies = []
    for ref in refs:
        result = get_result_by_validation_person(validate_person, all_results[ref])
        accuracies.append(max(result["history"]["val_accuracy"]))
    best_ref_index = accuracies.index(max(accuracies))
    best_ref = refs[best_ref_index]
    results = [get_result_by_validation_person(validate_person, all_results[best_ref])]
    
    metric_results = get_average_metrics(accuracy_score, None)
    
    data.append({
        "fold": validate_person,
        "frame": results[0]["meta"]["frames"],
        "val_accuracy": max(accuracies),
        "test_accuracy": metric_results[0]
    })
# data

In [34]:
df = pd.DataFrame.from_dict(data)
df = df.set_index("fold")
df

      frame  val_accuracy  test_accuracy
fold
1        55      0.930000       0.920000
2        69      0.980000       0.929412
3        69      0.929412       0.852632
4        62      0.936842       0.850000
5        55      0.900000       0.990000
6        62      1.000000       0.883495
7        55      0.941748       0.950000
8        69      1.000000       1.000000
9        55      1.000000       0.900000
10       55      0.940000       0.980000
11       55      0.990000       0.910000
12       62      0.960000       0.970000

In [35]:
df["test_accuracy"].mean()

0.9279615407736933

In [36]:
df["frame"].value_counts()

frame
55    6
69    3
62    3
Name: count, dtype: int64