In [1]:
import pandas as pd

In [2]:
base_path = "../00_datasets/dataset_output/include50/"

In [15]:
with open(base_path + "include50_train.txt") as file:
    train_signs = [line.rstrip() for line in file]

In [16]:
with open(base_path + "include50_test.txt") as file:
    test_signs = [line.rstrip() for line in file]

In [17]:
with open(base_path + "include50_val.txt") as file:
    val_signs = [line.rstrip() for line in file]

In [6]:
df = pd.read_csv(base_path + "include50_openpose.csv")

In [7]:
df = df[df["frame"] == 0]

In [8]:
df

,Unnamed: 0,category,video_name,frame,hand_0_0_x,hand_0_0_y,hand_0_0_z,hand_0_1_x,hand_0_1_y,hand_0_1_z,...,pose_22_y,pose_22_z,pose_23_x,pose_23_y,pose_23_z,pose_24_x,pose_24_y,pose_24_z,missing_hand,missing_face
0,0,1. loud,Adjectives\1. loud\MVI_5177.MOV,0,0.604532,0.777408,0.363928,0.591513,0.806553,0.604357,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
56,56,1. loud,Adjectives\1. loud\MVI_5178.MOV,0,0.602066,0.774227,0.378203,0.589384,0.800113,0.635507,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
120,120,1. loud,Adjectives\1. loud\MVI_5179.MOV,0,0.608191,0.762516,0.473886,0.596261,0.787804,0.636563,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
186,186,1. loud,Adjectives\1. loud\MVI_5257.MOV,0,0.586733,0.648375,0.066359,0.580327,0.707599,0.207504,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
238,238,1. loud,Adjectives\1. loud\MVI_5258.MOV,0,0.573028,0.784899,0.539296,0.558977,0.799172,0.646028,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260275,200853,9. Technology,Society\9. Technology\MVI_8691.MP4,0,0.580817,0.836595,0.613380,0.571384,0.856014,0.634817,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
260337,200915,9. Technology,Society\9. Technology\MVI_8692.MP4,0,0.576199,0.833876,0.629706,0.565776,0.853289,0.632433,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
260400,200978,9. Technology,Society\9. Technology\MVI_8951.MP4,0,0.562758,0.759590,0.687058,0.553144,0.775970,0.792343,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
260469,201047,9. Technology,Society\9. Technology\MVI_8952.MP4,0,0.564328,0.762401,0.709302,0.555253,0.779269,0.800806,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False
260543,201121,9. Technology,Society\9. Technology\MVI_8953.MP4,0,0.565388,0.760174,0.599573,0.556729,0.777033,0.662213,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False

In [9]:
train_signs

['Seasons/63. Winter/MVI_4997.MOV',
 'Jobs/89. Waiter/MVI_5334.MOV',
 'Animals/6. Mouse/MVI_2994.MOV',
 'Places/30. Hospital/MVI_3316.MOV',
 'Pronouns/42. he/MVI_0008.MOV',
 'Adjectives/6. Ugly/MVI_9579.MOV',
 'Adjectives/83. big large/MVI_5125.MOV',
 'Society/23. God/MVI_8996.MOV',
 'Home/38. Page/MVI_8809.MOV',
 'Jobs/93. Soldier/MVI_4777.MOV',
 'Days_and_Time/73. Today/MVI_5033.MOV',
 'Means_of_Transportation/9. Train/MVI_3110.MOV',
 'People/63. Baby/MVI_5236.MOV',
 'Jobs/84. Teacher/MVI_4745.MOV',
 'Animals/5. Cow/MVI_8570.MOV',
 'Places/20. Street or Road/MVI_3273.MOV',
 'People/59. Daughter/MVI_5076.MOV',
 'Colours/51. Brown/MVI_5051.MOV',
 'People/74. Queen/MVI_5273.MOV',
 'Colours/49. Blue/MVI_5043.MOV',
 'Adjectives/2. quiet/MVI_9538.MOV',
 'Jobs/91. Priest/MVI_4771.MOV',
 'Society/7. Team/MVI_4277.MOV',
 'Means_of_Transportation/13. Bicycle/MVI_3181.MOV',
 'Animals/7. Horse/MVI_3055.MOV',
 'Pronouns/42. he/MVI_9889.MOV',
 'Home/31. Kitchen/MVI_4897.MOV',
 'Days_and_Time/Second (Number)/MVI_5506.MOV',
 'Adjectives/79. short/MVI_5110.MOV',
 'Animals/4. Bird/MVI_3096.MOV',
 'Jobs/97. Reporter/MVI_5367.MOV',
 'People/64. Man/MVI_4227.MOV',
 'Pronouns/43. she/MVI_0012.MOV',
 'Greetings/50. Alright/MVI_0097.MOV',
 'Means_of_Transportation/9. Train/MVI_8579.MOV',
 'Seasons/64. Fall/MVI_5000.MOV',
 'People/77. Boy/MVI_5286.MOV',
 'Society/13. Attack/MVI_4837.MOV',
 'Pronouns/41. you/MVI_0015.MOV',
 'Colours/56. Grey/MVI_3746.MOV',
 'People/62. Parent/MVI_5084.MOV',
 'Clothes/42. T-Shirt/MVI_3704.MOV',
 'Colours/47. Red/MVI_8612.MOV',
 'Adjectives/18. curved/MVI_9635.MOV',
 'People/77. Boy/MVI_5285.MOV',
 'Animals/6. Mouse/MVI_3100.MOV',
 'Places/29. Library/MVI_3556.MOV',
 'Animals/2. Cat/MVI_2983.MOV',
 'Adjectives/89. warm/MVI_5143.MOV',
 'Electronics/60. Radio/MVI_9121.MOV',
 'Home/50. Tool/MVI_4454.MOV',
 'Places/34. Ground/MVI_3579.MOV',
 'Days_and_Time/72. Saturday/MVI_5467.MOV',
 'Society/22. Science/MVI_8993.MOV',
 'People/80. Adult/MVI_5296.MOV',
 'Adjectives/21. tight/MVI_9649.MOV',
 'Adjectives/93. young/MVI_9267.MOV',
 'Jobs/86. Lawyer/MVI_5320.MOV',
 'Home/49. Ring/MVI_9086.MOV',
 'Jobs/85. Student/MVI_5314.MOV',
 'Greetings/49. How are you/MVI_9919.MOV',
 'Adjectives/96. wet/MVI_5323.MOV',
 'People/72. Wife/MVI_4093.MOV',
 'Pronouns/42. he/MVI_9890.MOV',
 'Society/20. Price/MVI_4328.MOV',
 'People/79. Child/MVI_4992.MOV',
 'Days_and_Time/68. Tuesday/MVI_9145.MOV',
 'Greetings/49. How are you/MVI_9960.MOV',
 'Adjectives/2. quiet/MVI_5338.MOV',
 'Seasons/61. Summer/MVI_4565.MOV',
 'Animals/1. Dog/MVI_3029.MOV',
 'Adjectives/31. strong/MVI_9815.MOV',
 'Home/36. Soap/MVI_8801.MOV',
 'Adjectives/1. loud/MVI_9449.MOV',
 'Colours/50. Yellow/MVI_4028.MOV',
 'Society/1. Religion/MVI_4798.MOV',
 'Places/30. Hospital/MVI_3560.MOV',
 'Home/49. Ring/MVI_4450.MOV',
 'Home/24. Table/MVI_8752.MOV',
 'Electronics/53. Fan/MVI_9098.MOV',
 'Colours/49. Blue/MVI_5045.MOV',
 'Home/48. Card/MVI_9084.MOV',
 'Electronics/53. Fan/MVI_4964.MOV',
 'Clothes/42. T-Shirt/MVI_8606.MOV',
 'Days_and_Time/79. Hour/MVI_9180.MOV',
 'Places/28. Store or Shop/MVI_3475.MOV',
 'Adjectives/32. weak/MVI_9821.MOV',
 'Places/18. City/MVI_3347.MOV',
 'Clothes/37. Hat/MVI_5006.MOV',
 'Adjectives/12. poor/MVI_9737.MOV',
 'Adjectives/4. sad/MVI_9722.MOV',
 'Electronics/52. Lamp/MVI_4962.MOV',
 'Adjectives/98. sick/MVI_9282.MOV',
 'Means_of_Transportation/15. Boat/MVI_3191.MOV',
 'Home/24. Table/MVI_9001.MOV',
 'Clothes/41. Shirt/MVI_4880.MOV',
 'Greetings/56. Pleased/MVI_0062.MOV',
 'Clothes/39. Suit/MVI_3992.MOV',
 'Means_of_Transportation/12. Truck/MVI_8586.MOV',
 'Seasons/62. Spring/MVI_5428.MOV',
 'Adjectives/80. tall/MVI_5115.MOV',
 'Means_of_Transportation/17. Transportation/MVI_8598.MOV',
 'Clothes/37. Hat/MVI_3836.MOV',
 'Home/44. Telephone/MVI_4938.MOV',
 'Adjectives/78. long/MVI_5107.MOV',
 'Jobs/91. Priest/MVI_4490.MOV',
 'Places/33. India/MVI_3328.MOV',
 'Places/29. Library/MVI_3312.MOV',
 'Colours/52. Pink/MVI_4912.MOV',
 'Means_of_Transportation/16. train ticket/MVI_3195.MOV',
 'Days_and_Time/86. Time/MVI_4667.MOV',
 'Electronics/52. Lamp/MVI_5386.MOV',
 'People/67. Sister/MVI_3784.MOV',
 'Colours/47. Red/MVI_3867.MOV',
 'Means_of_Transportation/13. Bicycle/MVI_3244.MOV',
 'Places/27. Park/MVI_3305.MOV',
 'Jobs/97. Reporter/MVI_4512.MOV',
 'Days_and_Time/85. Night/MVI_5523.MOV',
 'Electronics/59. Television/MVI_4559.MOV',
 'People/68. Family/MVI_3933.MOV',
 'Means_of_Transportation/14. Bus/MVI_4186.MOV',
 'Means_of_Transportation/13. Bicycle/MVI_8588.MOV',
 'Adjectives/80. tall/MVI_9224.MOV',
 'Adjectives/33. dead/MVI_9700.MOV',
 'Adjectives/86. fast/MVI_5135.MOV',
 'Colours/53. Orange/MVI_4036.MOV',
 'Places/30. Hospital/MVI_3480.MOV',
 'Places/32. Market/MVI_3572.MOV',
 'Adjectives/81. wide/MVI_5117.MOV',
 'Days_and_Time/68. Tuesday/MVI_5014.MOV',
 'Days_and_Time/66. Sunday/MVI_5442.MOV',
 'People/69. Grandfather/MVI_8636.MOV',
 'Adjectives/96. wet/MVI_5166.MOV',
 'Clothes/37. Hat/MVI_3690.MOV',
 'People/60. Mother/MVI_5079.MOV',
 'Home/26. Bed/MVI_9008.MOV',
 'Adjectives/36. light/MVI_9712.MOV',
 'Colours/55. White/MVI_5209.MOV',
 'Seasons/Ex. Monsoon/MVI_4672.MOV',
 'People/81. Friend/MVI_4122.MOV',
 'Greetings/50. Alright/MVI_9923.MOV',
 'Society/4. Money/MVI_8938.MOV',
 'Means_of_Transportation/10. Plane/MVI_3172.MOV',
 'Days_and_Time/80. Minute/MVI_9182.MOV',
 'Means_of_Transportation/16. train ticket/MVI_3133.MOV',
 'Adjectives/29. clean/MVI_9808.MOV',
 'Places/34. Ground/MVI_3415.MOV',
 'Days_and_Time/83. Afternoon/MVI_9191.MOV',
 'Adjectives/79. short/MVI_5111.MOV',
 'Adjectives/87. hot/MVI_5296.MOV',
 'People/71. Husband/MVI_5262.MOV',
 'Adjectives/5. Beautiful/MVI_9571.MOV',
 'Days_and_Time/77. Month/MVI_5044.MOV',
 'Greetings/49. How are you/MVI_0036.MOV',
 'Colours/55. White/MVI_4921.MOV',
 'People/70. Grandmother/MVI_3795.MOV',
 'Seasons/61. Summer/MVI_9123.MOV',
 'People/59. Daughter/MVI_5075.MOV',
 'Days_and_Time/77. Month/MVI_5045.MOV',
 'Animals/4. Bird/MVI_3095.MOV',
 'Adjectives/12. poor/MVI_9601.MOV',
 'Pronouns/46. you (plural)/MVI_0024.MOV',
 'Society/22. Science/MVI_4337.MOV',
 'Home/36. Soap/MVI_4395.MOV',
 'Adjectives/99. healthy/MVI_9286.MOV',
 'Clothes/45. Pocket/MVI_4205.MOV',
 'Greetings/55. Thank you/MVI_9986.MOV',
 'Society/17. Sport/MVI_8977.MOV',
 'Adjectives/84. small little/MVI_9319.MOV',
 'Days_and_Time/79. Hour/MVI_4642.MOV',
 'Greetings/51. Good Morning/MVI_9970.MOV',
 'Society/14. Election/MVI_8969.MOV',
 'Days_and_Time/78. Year/MVI_9176.MOV',
 'Days_and_Time/67. Monday/MVI_5448.MOV',
 'Adjectives/99. healthy/MVI_9532.MOV',
 'Adjectives/21. tight/MVI_9771.MOV',
 'Colours/52. Pink/MVI_4034.MOV',
 'Days_and_Time/72. Saturday/MVI_9159.MOV',
 'Adjectives/7. Deaf/MVI_9848.MOV',
 'Colours/50. Yellow/MVI_5193.MOV',
 'Adjectives/94. good/MVI_5159.MOV',
 'People/82. Player/MVI_5148.MOV',
 'Adjectives/15. expensive/MVI_9613.MOV',
 'Greetings/54. Good night/MVI_005_6.MOV',
 'Places/18. City/MVI_3346.MOV',
 'Adjectives/3. happy/MVI_9541.MOV',
 'Home/50. Tool/MVI_9088.MOV',
 'Clothes/37. Hat/MVI_3688.MOV',
 'Days_and_Time/72. Saturday/MVI_5468.MOV',
 'People/75. President/MVI_5274.MOV',
 'Places/25. Office/MVI_3675.MOV',
 'Colours/53. Orange/MVI_8618.MOV',
 'Days_and_Time/73. Today/MVI_4617.MOV',
 'Adjectives/5. Beautiful/MVI_9724.MOV',
 'Adjectives/12. poor/MVI_9739.MOV',
 'People/82. Player/MVI_4247.MOV',
 'Clothes/41. Shirt/MVI_4879.MOV',
 'Seasons/64. Fall/MVI_9132.MOV',
 'Places/19. House/Extra/MVI_3439.MOV',
 'Adjectives/8. Blind/MVI_9586.MOV',
 'Clothes/41. Shirt/MVI_3701.MOV',
 'Places/19. House/MVI_3593.MOV',
 'Days_and_Time/66. Sunday/MVI_5444.MOV',
 'People/69. Grandfather/MVI_3792.MOV',
 'Home/34. Pen/MVI_4389.MOV',
 'Animals/4. Bird/MVI_2987.MOV',
 'Animals/6. Mouse/MVI_2993.MOV',
 'Electronics/55. Computer/MVI_4541.MOV',
 'Pronouns/47. they/MVI_9980.MOV',
 'Adjectives/89. warm/MVI_5224.MOV',
 'People/69. Grandfather/MVI_4085.MOV',
 'Adjectives/29. clean/MVI_9679.MOV',
 'Days_and_Time/72. Saturday/MVI_4611.MOV',
 'People/71. Husband/MVI_5113.MOV',
 'Means_of_Transportation/14. Bus/MVI_3248.MOV',
 'Pronouns/43. she/MVI_0011.MOV',
 'Colours/53. Orange/MVI_4037.MOV',
 'Animals/7. Horse/MVI_3022.MOV',
 'Animals/8. Animal/MVI_3084.MOV',
 'Home/40. Paint/MVI_8818.MOV',
 'Greetings/52. Good afternoon/MVI_9975.MOV',
 'Home/35. Photograph/MVI_4392.MOV',
 'Clothes/45. Pocket/MVI_3861.MOV',
 'Clothes/38. Dress/MVI_8601.MOV',
 'Adjectives/34. alive/MVI_9828.MOV',
 'Places/27. Park/MVI_3383.MOV',
 'Adjectives/78. long/MVI_9219.MOV',
 'People/70. Grandmother/MVI_4088.MOV',
 'Seasons/61. Summer/MVI_4568.MOV',
 'Colours/53. Orange/MVI_4917.MOV',
 'Clothes/37. Hat/MVI_5008.MOV',
 'People/59. Daughter/MVI_4934.MOV',
 'Adjectives/80. tall/MVI_9308.MOV',
 'Home/37. Book/MVI_4401.MOV',
 'Days_and_Time/70. Thursday/MVI_5020.MOV',
 'Jobs/84. Teacher/MVI_4459.MOV',
 'Jobs/92. Police/MVI_4492.MOV',
 'Adjectives/26. hard/MVI_9667.MOV',
 'Home/31. Kitchen/MVI_8780.MOV',
 'Home/40. Paint/MVI_8821.MOV',
 'People/70. Grandmother/MVI_4089.MOV',
 'Places/27. Park/MVI_3471.MOV',
 'Electronics/54. Cell phone/MVI_4967.MOV',
 'Society/6. Marriage/MVI_8679.MOV',
 'Places/34. Ground/MVI_3580.MOV',
 'Means_of_Transportation/10. Plane/MVI_3236.MOV',
 'Clothes/38. Dress/MVI_5009.MOV',
 'Means_of_Transportation/13. Bicycle/MVI_3151.MOV',
 'Animals/5. Cow/MVI_3049.MOV',
 'Adjectives/9. Nice/MVI_9588.MOV',
 'Society/9. Technology/MVI_8690.MOV',
 'Colours/56. Grey/MVI_3748.MOV',
 'Colours/57. Colour/MVI_8622.MOV',
 'Jobs/90. Secretary/MVI_4485.MOV',
 'Places/21. Train Station/MVI_3358.MOV',
 'Clothes/42. T-Shirt/MVI_3850.MOV',
 'Adjectives/91. new/MVI_5229.MOV',
 'Adjectives/97. dry/MVI_9278.MOV',
 'People/82. Player/MVI_5305.MOV',
 'Adjectives/86. fast/MVI_9485.MOV',
 'Adjectives/90. cool/MVI_9418.MOV',
 'Adjectives/89. warm/MVI_5141.MOV',
 'Days_and_Time/85. Night/MVI_4665.MOV',
 'Adjectives/78. long/MVI_9378.MOV',
 'Jobs/94. Artist/MVI_4501.MOV',
 'Adjectives/90. cool/MVI_5226.MOV',
 'Greetings/54. Good night/MVI_0057.MOV',
 'Means_of_Transportation/12. Truck/MVI_3214.MOV',
 'Adjectives/6. Ugly/MVI_9577.MOV',
 'Colours/56. Grey/MVI_4924.MOV',
 'Society/15. Newspaper/MVI_8714.MOV',
 'Home/48. Card/MVI_4951.MOV',
 'Days_and_Time/67. Monday/MVI_4591.MOV',
 'People/76. Neighbour/MVI_3813.MOV',
 'Home/42. Paper/MVI_9058.MOV',
 'Colours/51. Brown/MVI_4910.MOV',
 'Places/24. School/MVI_3459.MOV',
 'People/65. Woman/MVI_5092.MOV',
 'Electronics/58. Camera/MVI_5408.MOV',
 'Pronouns/44. it/MVI_9938.MOV',
 'Places/25. Office/MVI_3460.MOV',
 'Jobs/93. Soldier/MVI_4495.MOV',
 'Greetings/53. Good evening/MVI_0106.MOV',
 'Adjectives/99. healthy/MVI_5332.MOV',
 'Adjectives/93. young/MVI_5313.MOV',
 'Jobs/84. Teacher/MVI_4744.MOV',
 'Home/40. Paint/MVI_4415.MOV',
 'Clothes/41. Shirt/MVI_5020.MOV',
 'Means_of_Transportation/9. Train/MVI_3203.MOV',
 'Means_of_Transportation/10. Plane/MVI_3115.MOV',
 'Days_and_Time/67. Monday/MVI_5447.MOV',
 'People/61. Father/MVI_5080.MOV',
 'Adjectives/96. wet/MVI_9517.MOV',
 'Pronouns/40. I/MVI_9958.MOV',
 'Home/32. Bathroom/MVI_4381.MOV',
 'Adjectives/3. happy/MVI_9374.MOV',
 'Days_and_Time/71. Friday/MVI_5464.MOV',
 'Places/22. Restaurant/MVI_3529.MOV',
 'Adjectives/82. narrow/MVI_9230.MOV',
 'Electronics/55. Computer/MVI_5397.MOV',
 'People/66. Brother/MVI_5097.MOV',
 'Colours/53. Orange/MVI_3738.MOV',
 'Clothes/37. Hat/MVI_3986.MOV',
 'Clothes/44. Shoes/MVI_5175.MOV',
 'Places/22. Restaurant/MVI_3528.MOV',
 'Society/10. Energy/MVI_8954.MOV',
 'Home/28. Window/MVI_9015.MOV',
 'People/74. Queen/MVI_8641.MOV',
 'Society/14. Election/MVI_4840.MOV',
 'Home/39. Key/MVI_9050.MOV',
 'Society/1. Religion/MVI_8658.MOV',
 'Home/29. Door/MVI_8772.MOV',
 'Home/49. Ring/MVI_4954.MOV',
 'Colours/55. White/MVI_4043.MOV',
 'People/74. Queen/MVI_4973.MOV',
 'Pronouns/41. you/MVI_9960.MOV',
 'Society/22. Science/MVI_4863.MOV',
 'Home/38. Page/MVI_8812.MOV',
 'Adjectives/98. sick/MVI_5171.MOV',
 'People/75. President/MVI_4103.MOV',
 'People/72. Wife/MVI_5266.MOV',
 'Adjectives/94. good/MVI_9349.MOV',
 'People/71. Husband/MVI_4090.MOV',
 'Jobs/87. Doctor/MVI_8874.MOV',
 'Adjectives/87. hot/MVI_9329.MOV',
 'Pronouns/42. he/MVI_9892.MOV',
 'Means_of_Transportation/12. Truck/MVI_3119.MOV',
 'Home/41. Letter/MVI_8824.MOV',
 'People/65. Woman/MVI_5240.MOV',
 'Animals/8. Animal/MVI_3000.MOV',
 'Places/30. Hospital/MVI_3482.MOV',
 'People/69. Grandfather/MVI_5104.MOV',
 'Places/27. Park/MVI_3629.MOV',
 'Adjectives/95. bad/MVI_5243.MOV',
 'Adjectives/89. warm/MVI_9416.MOV',
 'Days_and_Time/72. Saturday/MVI_5466.MOV',
 'Seasons/62. Spring/MVI_4569.MOV',
 'People/72. Wife/MVI_4964.MOV',
 'Colours/52. Pink/MVI_4914.MOV',
 'Adjectives/93. young/MVI_5237.MOV',
 'People/72. Wife/MVI_5265.MOV',
 'Pronouns/47. they/MVI_9951.MOV',
 'Jobs/84. Teacher/MVI_4458.MOV',
 'Days_and_Time/72. Saturday/MVI_9157.MOV',
 'Society/23. God/MVI_8746.MOV',
 'Pronouns/45. we/MVI_0017.MOV',
 'People/78. Girl/MVI_5136.MOV',
 'Adjectives/84. small little/MVI_9400.MOV',
 'Adjectives/89. warm/MVI_5303.MOV',
 'Home/25. Chair/MVI_9004.MOV',
 'Society/3. Medicine/MVI_8935.MOV',
 'Seasons/65. Season/MVI_9137.MOV',
 'Clothes/39. Suit/MVI_5014.MOV',
 'People/81. Friend/MVI_5146.MOV',
 'Days_and_Time/66. Sunday/MVI_9141.MOV',
 'Adjectives/19. male/MVI_9763.MOV',
 'Adjectives/11. rich/MVI_9733.MOV',
 'Adjectives/93. young/MVI_5314.MOV',
 'Adjectives/87. hot/MVI_5295.MOV',
 'Places/19. House/MVI_3596.MOV',
 'Adjectives/80. tall/MVI_9307.MOV',
 'Society/16. Gun/MVI_8718.MOV',
 'Electronics/55. Computer/MVI_4970.MOV',
 'Society/19. Ball/MVI_8730.MOV',
 'Society/19. Ball/MVI_8984.MOV',
 'Adjectives/24. low/MVI_9786.MOV',
 'Days_and_Time/78. Year/MVI_9178.MOV',
 'Jobs/95. Author/MVI_5361.MOV',
 'Adjectives/81. wide/MVI_5278.MOV',
 'People/74. Queen/MVI_3807.MOV',
 'Means_of_Transportation/11. Car/MVI_3174.MOV',
 'Jobs/94. Artist/MVI_4780.MOV',
 'Colours/54. Black/MVI_5207.MOV',
 'Animals/7. Horse/MVI_3105.MOV',
 'Days_and_Time/82. Morning/MVI_9190.MOV',
 'Home/30. Bedroom/MVI_9020.MOV',
 'Adjectives/1. loud/MVI_9535.MOV',
 'People/81. Friend/MVI_3977.MOV',
 'Adjectives/89. warm/MVI_9417.MOV',
 'Animals/4. Bird/MVI_3011.MOV',
 'Adjectives/9. Nice/MVI_9589.MOV',
 'People/64. Man/MVI_4949.MOV',
 'Adjectives/79. short/MVI_5189.MOV',
 'Society/17. Sport/MVI_8723.MOV',
 'Clothes/43. Pant/MVI_5172.MOV',
 'People/59. Daughter/MVI_5222.MOV',
 'Pronouns/44. it/MVI_9898.MOV',
 'Clothes/42. T-Shirt/MVI_4002.MOV',
 'People/83. Crowd/MVI_8650.MOV',
 'Days_and_Time/79. Hour/MVI_9181.MOV',
 'Days_and_Time/71. Friday/MVI_4607.MOV',
 'Days_and_Time/71. Friday/MVI_9156.MOV',
 'People/81. Friend/MVI_5299.MOV',
 'People/62. Parent/MVI_4943.MOV',
 'Pronouns/41. you/MVI_9999.MOV',
 'Means_of_Transportation/15. Boat/MVI_3221.MOV',
 'Means_of_Transportation/17. Transportation/MVI_3137.MOV',
 'Days_and_Time/71. Friday/MVI_5026.MOV',
 'Clothes/40. Skirt/MVI_5164.MOV',
 'People/69. Grandfather/MVI_5255.MOV',
 'Jobs/94. Artist/MVI_4781.MOV',
 'Electronics/52. Lamp/MVI_9095.MOV',
 'People/80. Adult/MVI_3972.MOV',
 'Adjectives/3. happy/MVI_5184.MOV',
 'Clothes/38. Dress/MVI_3696.MOV',
 'Means_of_Transportation/9. Train/MVI_3141.MOV',
 'Colours/47. Red/MVI_4897.MOV',
 'Adjectives/19. male/MVI_9766.MOV',
 'Jobs/86. Lawyer/MVI_8873.MOV',
 'Places/22. Restaurant/MVI_3607.MOV',
 'Means_of_Transportation/12. Truck/MVI_4179.MOV',
 'Greetings/54. Good night/MVI_0056.MOV',
 'Places/24. School/MVI_3538.MOV',
 'Adjectives/87. hot/MVI_9328.MOV',
 'Adjectives/85. slow/MVI_5212.MOV',
 'Jobs/91. Priest/MVI_4772.MOV',
 'Clothes/46. Clothing/MVI_4016.MOV',
 'Places/35. Bank/MVI_3661.MOV',
 'Home/28. Window/MVI_4882.MOV',
 'Electronics/59. Television/MVI_5412.MOV',
 'Greetings/53. Good evening/MVI_9977.MOV',
 'Adjectives/10. Mean/MVI_9729.MOV',
 'Home/40. Paint/MVI_8817.MOV',
 'Society/17. Sport/MVI_8725.MOV',
 'Colours/53. Orange/MVI_4038.MOV',
 'Jobs/99. Job/MVI_4522.MOV',
 'Colours/56. Grey/MVI_4217.MOV',
 'Adjectives/92. old/MVI_9425.MOV',
 'Clothes/37. Hat/MVI_4197.MOV',
 'Adjectives/87. hot/MVI_5137.MOV',
 'Pronouns/43. she/MVI_0075.MOV',
 'Society/18. Exercise/MVI_8729.MOV',
 'Days_and_Time/70. Thursday/MVI_9153.MOV',
 'Days_and_Time/71. Friday/MVI_5463.MOV',
 'Days_and_Time/76. Week/MVI_5485.MOV',
 'Society/10. Energy/MVI_8696.MOV',
 'Adjectives/97. dry/MVI_9439.MOV',
 'Adjectives/3. happy/MVI_9376.MOV',
 'Places/29. Library/MVI_3479.MOV',
 'Electronics/52. Lamp/MVI_5383.MOV',
 'Places/26. University/MVI_3466.MOV',
 'Home/46. Box/MVI_9078.MOV',
 'Adjectives/93. young/MVI_9509.MOV',
 'Home/48. Card/MVI_9082.MOV',
 'Places/26. University/MVI_3377.MOV',
 'Days_and_Time/79. Hour/MVI_5497.MOV',
 'Adjectives/15. expensive/MVI_9616.MOV',
 'Places/33. India/MVI_3651.MOV',
 'Pronouns/42. he/MVI_0006.MOV',
 'Adjectives/93. young/MVI_9265.MOV',
 'Greetings/49. How are you/MVI_0035.MOV',
 'Adjectives/1. loud/MVI_5179.MOV',
 'Electronics/59. Television/MVI_5413.MOV',
 'Society/20. Price/MVI_4330.MOV',
 'Society/17. Sport/MVI_8976.MOV',
 'People/66. Brother/MVI_3778.MOV',
 'Society/6. Marriage/MVI_4271.MOV',
 'Clothes/41. Shirt/MVI_5167.MOV',
 'Colours/48. Green/MVI_3871.MOV',
 'Society/6. Marriage/MVI_8677.MOV',
 'People/66. Brother/MVI_4230.MOV',
 'Seasons/65. Season/MVI_4581.MOV',
 'Adjectives/99. healthy/MVI_9367.MOV',
 'Jobs/91. Priest/MVI_4487.MOV',
 'Places/18. City/MVI_3432.MOV',
 'Greetings/53. Good evening/MVI_9943.MOV',
 'Colours/51. Brown/MVI_8616.MOV',
 'Places/21. Train Station/MVI_3602.MOV',
 'Means_of_Transportation/9. Train/MVI_8580.MOV',
 'Places/33. India/MVI_3576.MOV',
 'Colours/50. Yellow/MVI_3728.MOV',
 'Days_and_Time/76. Week/MVI_9169.MOV',
 'Home/24. Table/MVI_4871.MOV',
 'Electronics/57. Screen/MVI_5405.MOV',
 'Society/1. Religion/MVI_8927.MOV',
 'Electronics/53. Fan/MVI_5388.MOV',
 'Days_and_Time/76. Week/MVI_4629.MOV',
 'Home/39. Key/MVI_8814.MOV',
 'Pronouns/47. they/MVI_9952.MOV',
 'Pronouns/40. I/MVI_9880.MOV',
 'Adjectives/96. wet/MVI_9275.MOV',
 'Places/21. Train Station/MVI_3604.MOV',
 'Days_and_Time/70. Thursday/MVI_5459.MOV',
 'Seasons/61. Summer/MVI_5424.MOV',
 'Colours/57. Colour/MVI_3897.MOV',
 'Adjectives/25. soft/MVI_9662.MOV',
 'Places/32. Market/MVI_3648.MOV',
 'Society/12. Peace/MVI_8961.MOV',
 'Home/29. Door/MVI_8773.MOV',
 'Society/18. Exercise/MVI_8727.MOV',
 'Adjectives/81. wide/MVI_9468.MOV',
 'Places/36. Location/MVI_3343.MOV',
 'Clothes/38. Dress/MVI_4869.MOV',
 'Greetings/52. Good afternoon/MVI_9995.MOV',
 'Greetings/51. Good Morning/MVI_9969.MOV',
 'Clothes/39. Suit/MVI_3841.MOV',
 'People/70. Grandmother/MVI_4235.MOV',
 'Adjectives/29. clean/MVI_9809.MOV',
 'Home/26. Bed/MVI_9007.MOV',
 'Home/24. Table/MVI_4870.MOV',
 'Jobs/98. Actor/MVI_4519.MOV',
 'Greetings/52. Good afternoon/MVI_9996.MOV',
 'Colours/47. Red/MVI_3721.MOV',
 'People/68. Family/MVI_4081.MOV',
 'Animals/5. Cow/MVI_2990.MOV',
 'Places/18. City/MVI_3345.MOV',
 'People/80. Adult/MVI_4121.MOV',
 'Jobs/97. Reporter/MVI_4515.MOV',
 'Home/49. Ring/MVI_4451.MOV',
 'Colours/48. Green/MVI_3724.MOV',
 'Greetings/52. Good afternoon/MVI_9974.MOV',
 'Means_of_Transportation/11. Car/MVI_3117.MOV',
 'People/64. Man/MVI_5090.MOV',
 'Home/50. Tool/MVI_4958.MOV',
 'People/58. Son/MVI_3900.MOV',
 'Greetings/55. Thank you/MVI_0112.MOV',
 'Adjectives/98. sick/MVI_9281.MOV',
 'Days_and_Time/83. Afternoon/MVI_4658.MOV',
 'People/61. Father/MVI_5229.MOV',
 'Days_and_Time/80. Minute/MVI_4644.MOV',
 'Electronics/60. Radio/MVI_4988.MOV',
 'Home/24. Table/MVI_8750.MOV',
 'People/73. King/MVI_5268.MOV',
 'Adjectives/17. flat/MVI_9756.MOV',
 'People/71. Husband/MVI_5263.MOV',
 'Greetings/53. Good evening/MVI_9999.MOV',
 'Home/42. Paper/MVI_8826.MOV',
 'Pronouns/46. you (plural)/MVI_9977.MOV',
 'Adjectives/91. new/MVI_5148.MOV',
 'Electronics/58. Camera/MVI_5407.MOV',
 'Society/3. Medicine/MVI_4803.MOV',
 'People/82. Player/MVI_5303.MOV',
 'Greetings/48. Hello/MVI_0089.MOV',
 'Colours/54. Black/MVI_4040.MOV',
 'Clothes/37. Hat/MVI_3837.MOV',
 'Adjectives/14. thin/MVI_9611.MOV',
 'Means_of_Transportation/9. Train/MVI_3233.MOV',

In [10]:
"A".lower()

'a'

In [11]:
df["video_path"] = df.apply(lambda i: (i["video_name"].replace("\\", "/")).lower().replace(".mov", "").replace(".mp4", ""), axis=1)

In [12]:
videos = df["video_path"].unique()
videos

array(['adjectives/1. loud/mvi_5177', 'adjectives/1. loud/mvi_5178',
       'adjectives/1. loud/mvi_5179', ...,
       'society/9. technology/mvi_8951', 'society/9. technology/mvi_8952',
       'society/9. technology/mvi_8953'], dtype=object)

In [24]:
for video in train_signs:
    if video.lower().replace(".mov", "").replace(".mp4", "") not in videos:
        print(video)

Colours/47. Red/MVI_4018.MOV
Colours/55. White/MVI_5061.MOV
Colours/47. Red/MVI_4899.MOV
Colours/55. White/MVI_4923.MOV
Colours/47. Red/MVI_5185.MOV
Colours/55. White/MVI_3743.MOV
Colours/47. Red/MVI_5038.MOV
Colours/47. Red/MVI_3867.MOV
Colours/55. White/MVI_5062.MOV
Colours/47. Red/MVI_4207.MOV
Colours/54. Black/MVI_5058.MOV
Colours/47. Red/MVI_3721.MOV
Colours/55. White/MVI_3745.MOV
Places/28. Store or Shop/Extra/MVI_3636.MOV
Places/35. Bank/Extra/MVI_3339.MOV
Colours/55. White/MVI_4922.MOV
Colours/55. White/MVI_3891.MOV
Colours/47. Red/MVI_8612.MOV
Colours/55. White/MVI_4043.MOV
Colours/54. Black/MVI_5206.MOV
Colours/55. White/MVI_3892.MOV
Animals/4. Bird/Extra/MVI_3043.MOV
Colours/54. Black/MVI_3889.MOV
Colours/47. Red/MVI_5039.MOV
Adjectives/84. small little/extra/MVI_5209.MOV
Colours/54. Black/MVI_3887.MOV
Colours/47. Red/MVI_3720.MOV
Colours/55. White/MVI_4921.MOV
Colours/47. Red/MVI_3719.MOV
Colours/54. Black/MVI_4919.MOV
Colours/47. Red/MVI_4019.MOV
Colours/55. White/MVI_4044.MOV
Colours/47. Red/MVI_5184.MOV
Colours/55. White/MVI_5209.MOV
Colours/55. White/MVI_8620.MOV
Colours/55. White/MVI_3890.MOV
Places/23. Court/Extra/MVI_3368.MOV
Adjectives/79. short/extra/MVI_5192.MOV
Colours/54. Black/MVI_4040.MOV
Colours/54. Black/MVI_4918.MOV
Animals/4. Bird/Extra/MVI_3042.MOV
Places/23. Court/Extra/MVI_3613.MOV
Colours/55. White/MVI_4216.MOV
Places/23. Court/Extra/MVI_3288.MOV
Colours/54. Black/MVI_5059.MOV
Colours/54. Black/MVI_3888.MOV
Animals/4. Bird/Extra/MVI_3044.MOV
Colours/47. Red/MVI_3868.MOV
Animals/4. Bird/Extra/MVI_3041.MOV
Colours/54. Black/MVI_4215.MOV
Colours/55. White/MVI_4042.MOV
Colours/47. Red/MVI_5037.MOV
Places/28. Store or Shop/Extra/MVI_3637.MOV
Animals/4. Bird/Extra/MVI_3045.MOV
Places/35. Bank/Extra/MVI_3420.MOV
Colours/54. Black/MVI_8619.MOV
Colours/54. Black/MVI_5208.MOV
Colours/54. Black/MVI_3741.MOV
Colours/55. White/MVI_5210.MOV
Colours/54. Black/MVI_5060.MOV
Colours/47. Red/MVI_4017.MOV

In [22]:
for video in test_signs:
    if video.lower().replace(".mov", "").replace(".mp4", "") not in videos:
        print(video)

Colours/54. Black/MVI_4920.MOV
Colours/54. Black/MVI_3740.MOV
Colours/54. Black/MVI_3742.MOV
Colours/54. Black/MVI_5207.MOV
Colours/54. Black/MVI_4041.MOV
Colours/47. Red/MVI_5186.MOV
Colours/47. Red/MVI_4898.MOV
Colours/55. White/MVI_5211.MOV
Places/19. House/Extra/MVI_3439.MOV

In [23]:
for video in val_signs:
    if video.lower().replace(".mov", "").replace(".mp4", "") not in videos:
        print(video)

Colours/54. Black/MVI_4039.MOV
Colours/47. Red/MVI_3866.MOV
Colours/55. White/MVI_5063.MOV
Colours/55. White/MVI_3744.MOV
Colours/47. Red/MVI_4897.MOV

electronics/54. cell phone/mvi_9100.mp4
electronics/54. cell phone/mvi_9100.mov

In [48]:
for i, j in zip("electronics/54. cell phone/mvi_9100","electronics/54. cell phone/mvi_9100"):
    if not i == j:
        print(i)
        print(j)
        print("="*10)

In [43]:
df[df["category"] == "54. Cell phone"]

,Unnamed: 0,category,video_name,frame,hand_0_0_x,hand_0_0_y,hand_0_0_z,hand_0_1_x,hand_0_1_y,hand_0_1_z,...,pose_22_z,pose_23_x,pose_23_y,pose_23_z,pose_24_x,pose_24_y,pose_24_z,missing_hand,missing_face,video_path
91367,31945,54. Cell phone,Electronics\54. Cell phone\MVI_4537.MOV,0,0.578195,0.818914,0.532419,0.568959,0.846280,0.676307,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_4537
91415,31993,54. Cell phone,Electronics\54. Cell phone\MVI_4538.MOV,0,0.579216,0.824293,0.551517,0.569604,0.847677,0.658454,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_4538
91462,32040,54. Cell phone,Electronics\54. Cell phone\MVI_4539.MOV,0,0.580825,0.818924,0.563770,0.572716,0.844151,0.652641,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_4539
91515,32093,54. Cell phone,Electronics\54. Cell phone\MVI_4540.MOV,0,0.581863,0.827081,0.523649,0.573761,0.848687,0.533508,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_4540
91560,32138,54. Cell phone,Electronics\54. Cell phone\MVI_4967.MOV,0,0.551425,0.714889,0.501980,0.545693,0.732134,0.572838,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_4967
91615,32193,54. Cell phone,Electronics\54. Cell phone\MVI_4968.MOV,0,0.558089,0.720456,0.451768,0.552437,0.733598,0.474344,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_4968
91674,32252,54. Cell phone,Electronics\54. Cell phone\MVI_4969.MOV,0,0.555310,0.724867,0.424938,0.550418,0.738308,0.547613,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_4969
91742,32320,54. Cell phone,Electronics\54. Cell phone\MVI_5391.MOV,0,0.578981,0.799460,0.549257,0.566798,0.816477,0.669253,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_5391
91788,32366,54. Cell phone,Electronics\54. Cell phone\MVI_5392.MOV,0,0.571915,0.793934,0.560697,0.559843,0.813095,0.731759,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_5392
91841,32419,54. Cell phone,Electronics\54. Cell phone\MVI_5393.MOV,0,0.574762,0.788443,0.538186,0.561250,0.809365,0.642245,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_5393
91894,32472,54. Cell phone,Electronics\54. Cell phone\MVI_5394.MOV,0,0.575335,0.792504,0.586504,0.564390,0.811183,0.677011,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_5394
91954,32532,54. Cell phone,Electronics\54. Cell phone\MVI_9100.MP4,0,0.556972,0.772897,0.603953,0.547754,0.788572,0.675759,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_9100
92027,32605,54. Cell phone,Electronics\54. Cell phone\MVI_9101.MP4,0,0.554845,0.774242,0.585518,0.546309,0.790863,0.651818,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_9101
92096,32674,54. Cell phone,Electronics\54. Cell phone\MVI_9102.MP4,0,0.556965,0.774914,0.578294,0.548014,0.791551,0.670282,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,electronics/54. cell phone/mvi_9102